env:
  browser: true
  es6: true
  jest: true
extends: standard-with-typescript
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  project: tsconfig.json
rules: {
  "@typescript-eslint/strict-boolean-expressions": "warn"
}
